# Generated by Django 4.2.16 on 2026-05-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
