# Generated by Django 4.2.16 on 2026-05-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_patient_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['date_created'], name='patients_pa_date_cr_a0c501_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx'),
        ),
    ]
