# Generated by Django 4.2.16 on 2025-09-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_nextofkin_user_alter_permanentaddress_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialaddress',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='residentialaddress',
            name='phone2',
        ),
        migrations.AlterField(
            model_name='residentialaddress',
            name='national_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
