# Generated by Django 4.2.16 on 2026-03-31 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICD11Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('depth_in_kind', models.IntegerField(default=1)),
                ('is_residual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ICD-11 Block',
                'verbose_name_plural': 'ICD-11 Blocks',
                'db_table': 'icd11_blocks',
                'ordering': ['depth_in_kind', 'block_id'],
            },
        ),
        migrations.CreateModel(
            name='ICD11Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(max_length=500)),
                ('chapter_no', models.CharField(db_index=True, max_length=10)),
                ('chapter_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ICD-11 Chapter',
                'verbose_name_plural': 'ICD-11 Chapters',
                'db_table': 'icd11_chapters',
                'ordering': ['chapter_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ICD11Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('depth_in_kind', models.IntegerField(default=1)),
                ('is_leaf', models.BooleanField(default=False)),
                ('is_residual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='icd11.icd11block')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='icd11.icd11chapter')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='icd11.icd11category')),
            ],
            options={
                'verbose_name': 'ICD-11 Category',
                'verbose_name_plural': 'ICD-11 Categories',
                'db_table': 'icd11_categories',
                'ordering': ['depth_in_kind', 'code'],
            },
        ),
        migrations.AddField(
            model_name='icd11block',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='icd11.icd11chapter'),
        ),
        migrations.AddField(
            model_name='icd11block',
            name='parent_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='icd11.icd11block'),
        ),
        migrations.CreateModel(
            name='ICD11Grouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouping_type', models.CharField(choices=[('grouping1', 'Primary Grouping'), ('grouping2', 'Secondary Grouping'), ('grouping3', 'Tertiary Grouping'), ('grouping4', 'Quaternary Grouping'), ('grouping5', 'Quinary Grouping')], max_length=20)),
                ('grouping_value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupings', to='icd11.icd11category')),
            ],
            options={
                'verbose_name': 'ICD-11 Grouping',
                'verbose_name_plural': 'ICD-11 Groupings',
                'db_table': 'icd11_groupings',
                'unique_together': {('category', 'grouping_type')},
            },
        ),
        migrations.AddIndex(
            model_name='icd11category',
            index=models.Index(fields=['code'], name='icd11_categ_code_97297d_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11category',
            index=models.Index(fields=['depth_in_kind'], name='icd11_categ_depth_i_28a56a_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11category',
            index=models.Index(fields=['is_leaf'], name='icd11_categ_is_leaf_844777_idx'),
        ),
    ]
