# Generated by Django 4.2.16 on 2026-03-31 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encounters', '0001_initial'),
        ('patients', '0001_initial'),
        ('icd11', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD11Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_type', models.CharField(choices=[('primary', 'Primary Diagnosis'), ('secondary', 'Secondary Diagnosis'), ('complication', 'Complication'), ('comorbidity', 'Comorbidity'), ('provisional', 'Provisional Diagnosis'), ('differential', 'Differential Diagnosis'), ('rule_out', 'Rule Out')], default='primary', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('ruled_out', 'Ruled Out'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('clinical_description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='icd11.icd11category')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_confirmed', to=settings.AUTH_USER_MODEL)),
                ('diagnosed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_made', to=settings.AUTH_USER_MODEL)),
                ('encounter_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='encounters.encounterroute')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patient')),
            ],
            options={
                'verbose_name': 'ICD-11 Diagnosis',
                'verbose_name_plural': 'ICD-11 Diagnoses',
                'db_table': 'icd11_diagnoses',
                'ordering': ['-diagnosed_date'],
            },
        ),
        migrations.CreateModel(
            name='ICD11DiagnosisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_date', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='icd11.icd11diagnosis')),
            ],
            options={
                'verbose_name': 'ICD-11 Diagnosis History',
                'verbose_name_plural': 'ICD-11 Diagnosis Histories',
                'db_table': 'icd11_diagnosis_history',
                'ordering': ['-changed_date'],
            },
        ),
        migrations.AddIndex(
            model_name='icd11diagnosis',
            index=models.Index(fields=['patient', 'encounter_route'], name='icd11_diagn_patient_6386e5_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11diagnosis',
            index=models.Index(fields=['status'], name='icd11_diagn_status_580b88_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11diagnosis',
            index=models.Index(fields=['diagnosis_type'], name='icd11_diagn_diagnos_eda3aa_idx'),
        ),
        migrations.AddIndex(
            model_name='icd11diagnosis',
            index=models.Index(fields=['diagnosed_date'], name='icd11_diagn_diagnos_879025_idx'),
        ),
    ]
