# Generated by Django 4.2.16 on 2026-03-14 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDetailBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_records', to='pharmacies.batch')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_records', to='bills.bill')),
                ('prescription_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_records', to='pharmacies.prescriptiondetail')),
            ],
            options={
                'verbose_name': 'Prescription Detail Bill',
                'verbose_name_plural': 'Prescription Detail Bills',
                'ordering': ['-date_created'],
                'unique_together': {('prescription_detail', 'bill', 'batch')},
            },
        ),
    ]
