# Generated by Django 4.2.16 on 2026-03-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_prescriptiondetailbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('billed', 'Billed'), ('partly_paid', 'Partly Paid'), ('paid', 'Paid'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('paid', 'Paid'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
