# Generated by Django 4.2.16 on 2026-04-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_alter_prescription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
