# Generated by Django 4.2.16 on 2026-04-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_alter_brand_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-date_requested']},
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to='pharmacies.brand'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='pharmacies.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='pharmacies.batch'),
        ),
    ]
