# Generated by Django 4.2.16 on 2026-04-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0006_stockadjustmenttype_stockadjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustment',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='status',
        ),
    ]
