# Generated by Django 4.2.16 on 2026-05-08 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='encounter_route',
            field=models.ForeignKey(blank=True, help_text="Patient's location at the time of request (clinic or ward)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='encounters.encounterroute'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('partly_paid', 'Partly Paid'), ('paid', 'Paid'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Overall status based on payment and service delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequestdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('partly_paid', 'Partly Paid'), ('paid', 'Paid'), ('completed', 'Completed')], default='pending', help_text='Item-level status for payment and delivery', max_length=20),
        ),
    ]
