# Generated by Django 5.0.3 on 2026-06-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicerequest_encounter_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('partly_paid', 'Partly Paid'), ('paid', 'Paid'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='billed', help_text='Overall status based on payment and service delivery', max_length=20),
        ),
    ]
