# Generated by Django 5.2.6 on 2026-04-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent_specialty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entclerking',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='drughistory',
            name='drug_allergy',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='drughistory',
            name='on_medications',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='earexamination',
            name='left_facial_nerve_paralysis',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='earexamination',
            name='otorrhoea',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='earexamination',
            name='pinna_deformity',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='earexamination',
            name='right_facial_nerve_paralysis',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='earexamination',
            name='tragal_pinna_tenderness',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='acutely_ill_looking',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='chronically_ill_looking',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='cyanosis',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='dehydrated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='dyspnoeic',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='intercostal_subcostal_recession',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='jaundice',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='lymph_node',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='normal',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='pallor',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='tachypnoea',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generalexamination',
            name='weight_loss',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='headandneckhistory',
            name='facial_deformity',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='headandneckhistory',
            name='jaw_swelling',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='headandneckhistory',
            name='neck_swelling',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='laryngologyhistory',
            name='breathing_difficulty',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='laryngologyhistory',
            name='dysphagia',
            field=models.BooleanField(blank=True, default=None, help_text='Difficulty swallowing', null=True),
        ),
        migrations.AlterField(
            model_name='laryngologyhistory',
            name='excessive_throat_hawking',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='laryngologyhistory',
            name='halitosis',
            field=models.BooleanField(blank=True, default=None, help_text='Bad breath', null=True),
        ),
        migrations.AlterField(
            model_name='laryngologyhistory',
            name='hoarseness',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='laryngologyhistory',
            name='loss_of_taste',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='laryngologyhistory',
            name='lump_in_throat',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='laryngologyhistory',
            name='odynophagia',
            field=models.BooleanField(blank=True, default=None, help_text='Painful swallowing', null=True),
        ),
        migrations.AlterField(
            model_name='laryngologyhistory',
            name='snoring',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='laryngologyhistory',
            name='throat_pain',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='engorged_inferior_turbinate_left',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='engorged_inferior_turbinate_right',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='nasal_mass_left',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='nasal_mass_right',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='nasal_polyps_left',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='nasal_polyps_right',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='nasal_pyramid_deformed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='nasal_pyramid_normal',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='nose_bleeding_left',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='nose_bleeding_right',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='olfactory_intact',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='otorrhoea_left',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='otorrhoea_right',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='patent_nasal_cavity',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='septum_central',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nasalexamination',
            name='septum_deviated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='neckexamination',
            name='anterior_neck_mass',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='neckexamination',
            name='laryngeal_framework_preserved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='neckexamination',
            name='lateral_neck_mass',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='oralcavityoropharynxexamination',
            name='exudates',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='oralcavityoropharynxexamination',
            name='free_labial_buccal_sulci',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='oralcavityoropharynxexamination',
            name='free_retromolar_trigone',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='oralcavityoropharynxexamination',
            name='good_oral_hygiene',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='oralcavityoropharynxexamination',
            name='granular_posterior_pharyngeal_wall',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='oralcavityoropharynxexamination',
            name='halitosis',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='oralcavityoropharynxexamination',
            name='hyperaemia',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='oralcavityoropharynxexamination',
            name='tonsil_normal',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otologichistory',
            name='hearing_loss',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='otologichistory',
            name='otalgia',
            field=models.BooleanField(blank=True, default=None, help_text='Ear pain', null=True),
        ),
        migrations.AlterField(
            model_name='otologichistory',
            name='otorrhoea',
            field=models.BooleanField(blank=True, default=None, help_text='Ear discharge', null=True),
        ),
        migrations.AlterField(
            model_name='otologichistory',
            name='tinnitus',
            field=models.BooleanField(blank=True, default=None, help_text='Ringing in the ear', null=True),
        ),
        migrations.AlterField(
            model_name='otologichistory',
            name='vertigo',
            field=models.BooleanField(blank=True, default=None, help_text='Dizziness/spinning sensation', null=True),
        ),
        migrations.AlterField(
            model_name='pastmedicalsocialhistory',
            name='allergy',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pastmedicalsocialhistory',
            name='diabetes',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pastmedicalsocialhistory',
            name='history_of_pud',
            field=models.BooleanField(blank=True, default=None, help_text='Peptic Ulcer Disease', null=True),
        ),
        migrations.AlterField(
            model_name='pastmedicalsocialhistory',
            name='hypertension',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pastmedicalsocialhistory',
            name='migraine_headache',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rhinologichistory',
            name='anosmia',
            field=models.BooleanField(blank=True, default=None, help_text='Complete loss of smell', null=True),
        ),
        migrations.AlterField(
            model_name='rhinologichistory',
            name='excessive_sneezing',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rhinologichistory',
            name='facial_pain',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rhinologichistory',
            name='hyposmia',
            field=models.BooleanField(blank=True, default=None, help_text='Reduced sense of smell', null=True),
        ),
        migrations.AlterField(
            model_name='rhinologichistory',
            name='nasal_growth',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rhinologichistory',
            name='nasal_obstruction',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rhinologichistory',
            name='nose_bleeding',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rhinologichistory',
            name='rhinorrhea',
            field=models.BooleanField(blank=True, default=None, help_text='Runny nose', null=True),
        ),
    ]
