# Generated by Django 4.2.16 on 2025-09-04 06:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transfer',
            new_name='EncounterRoute',
        ),
        migrations.RenameModel(
            old_name='Encounter',
            new_name='Visit',
        ),
    ]
