# Generated by Django 4.2.16 on 2025-09-04 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('encounters', '0002_rename_transfer_encounterroute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='send_to',
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='encounterroute',
            name='transferred_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encounterroute',
            name='visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='encounters.visit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='send_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
