# Generated by Django 4.2.16 on 2025-09-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_clinic_options_alter_ward_options_and_more'),
        ('encounters', '0003_remove_visit_send_to_visit_visit_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounterroute',
            name='in_patient_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.ward'),
        ),
        migrations.AlterField(
            model_name='encounterroute',
            name='out_patient_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.clinic'),
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
