# Generated by Django 5.1.5 on 2025-07-02 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(verbose_name='Temperature (°C)')),
                ('weight', models.FloatField(verbose_name='Weight (kg)')),
                ('height', models.FloatField(verbose_name='Height (cm)')),
                ('bp', models.CharField(max_length=7, verbose_name='Blood Pressure')),
                ('spo2', models.FloatField(verbose_name='SpO2 (%)')),
                ('pulse', models.FloatField(verbose_name='Pulse (bpm)')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
