# Generated by Django 4.2.16 on 2026-03-13 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight (kg)')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height (cm)')),
                ('bp', models.CharField(blank=True, max_length=7, null=True, verbose_name='Blood Pressure')),
                ('spo2', models.FloatField(blank=True, null=True, verbose_name='SpO2 (%)')),
                ('pulse', models.FloatField(blank=True, null=True, verbose_name='Pulse (bpm)')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FluidBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_type', models.CharField(blank=True, choices=[('oral', 'Oral'), ('iv', 'IV Fluids'), ('ng', 'NG Tube'), ('other', 'Other')], max_length=20, null=True)),
                ('intake_volume', models.PositiveIntegerField(blank=True, help_text='Volume in ml', null=True)),
                ('intake_description', models.CharField(blank=True, max_length=255, null=True)),
                ('output_type', models.CharField(blank=True, choices=[('urine', 'Urine'), ('vomit', 'Vomit'), ('drain', 'Drain'), ('stool', 'Stool'), ('other', 'Other')], max_length=20, null=True)),
                ('output_volume', models.PositiveIntegerField(blank=True, help_text='Volume in ml', null=True)),
                ('output_description', models.CharField(blank=True, max_length=255, null=True)),
                ('net_balance', models.IntegerField(default=0, help_text='Intake - Output')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encounters.encounterroute')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_balance_records', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fluid Balance Record',
                'verbose_name_plural': 'Fluid Balance Records',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
