# Generated by Django 4.2.16 on 2025-09-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('triages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='bp',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='pulse',
            field=models.FloatField(blank=True, null=True, verbose_name='Pulse (bpm)'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='spo2',
            field=models.FloatField(blank=True, null=True, verbose_name='SpO2 (%)'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight (kg)'),
        ),
    ]
