# Generated by Django 4.2.16 on 2026-04-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('triages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encounters.encounterroute'),
        ),
    ]
