# Generated by Django 4.2.16 on 2025-09-06 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('triages', '0002_alter_triage_bp_alter_triage_height_alter_triage_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
