# Generated by Django 4.2.16 on 2026-03-13 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('si_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('requires_reference_range', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_complex', models.BooleanField(default=False)),
                ('si_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('requires_remark', models.BooleanField(default=False)),
                ('requires_reference_range', models.BooleanField(default=True)),
                ('lab_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lab.labunit')),
            ],
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('partly_billed', 'Partly Billed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_requests', to='patients.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_tests', models.ManyToManyField(blank=True, related_name='requests', to='lab.subtest')),
                ('tests', models.ManyToManyField(related_name='requests', to='lab.test')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='TestRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('partly_billed', 'Partly Billed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('sub_tests', models.ManyToManyField(blank=True, related_name='request_details', to='lab.subtest')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_details', to='lab.test')),
                ('test_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='lab.testrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tests', models.ManyToManyField(to='lab.test')),
            ],
        ),
        migrations.AddField(
            model_name='subtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tests', to='lab.test'),
        ),
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], max_length=10)),
                ('age_min', models.CharField(blank=True, max_length=100, null=True)),
                ('age_max', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Child', 'Child'), ('Any', 'Any')], max_length=10, null=True)),
                ('range_value', models.CharField(max_length=255)),
                ('sub_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='lab.subtest')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='lab.test')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('needs_retest', models.BooleanField(default=False)),
                ('reference_range', models.CharField(blank=True, max_length=255, null=True)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_result', to='lab.testrequestdetail')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.test')),
                ('test_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='lab.testrequest')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('needs_retest', models.BooleanField(default=False)),
                ('reference_range', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_test_results', to='lab.labresult')),
                ('sub_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.subtest')),
            ],
            options={
                'unique_together': {('lab_result', 'sub_test')},
            },
        ),
    ]
