# Generated by Django 5.1.6 on 2025-07-14 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='compound_id',
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='prepared_by',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='requested_id',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='verified_by',
        ),
        migrations.RenameField(
            model_name='testrequest',
            old_name='date_created',
            new_name='request_date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='patent_id',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='test_id',
        ),
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='is_complex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='test',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='requires_reference_range',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='requires_remark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='si_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrequest',
            name='tests',
            field=models.ManyToManyField(related_name='requests', to='lab.test'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='lab_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='lab.labunit'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], max_length=10)),
                ('age_min', models.CharField(blank=True, max_length=100, null=True)),
                ('age_max', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Child', 'Child'), ('Any', 'Any')], max_length=10, null=True)),
                ('range_value', models.CharField(max_length=255)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='lab.test')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.TextField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('result_date', models.DateTimeField(auto_now_add=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('needs_retest', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.test')),
                ('test_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='lab.testrequest')),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reference_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='lab.referencerange')),
            ],
        ),
        migrations.CreateModel(
            name='SubTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
                ('si_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('requires_reference_range', models.BooleanField(default=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tests', to='lab.test')),
            ],
        ),
        migrations.AddField(
            model_name='referencerange',
            name='sub_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='lab.subtest'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='sub_tests',
            field=models.ManyToManyField(blank=True, related_name='requests', to='lab.subtest'),
        ),
        migrations.CreateModel(
            name='SubTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(max_length=255)),
                ('is_critical', models.BooleanField(default=False)),
                ('needs_retest', models.BooleanField(default=False)),
                ('lab_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_test_results', to='lab.labresult')),
                ('reference_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_test_results', to='lab.referencerange')),
                ('sub_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.subtest')),
            ],
        ),
        migrations.CreateModel(
            name='TestPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tests', models.ManyToManyField(to='lab.test')),
            ],
        ),
        migrations.DeleteModel(
            name='CompoundTest',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
