# Generated by Django 4.2.16 on 2026-05-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_testrequest_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequestdetail',
            name='mls_comment',
            field=models.TextField(blank=True, help_text='Comments from MLS about this test result', null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('partly_billed', 'Partly Billed'), ('partly_paid', 'Partly Paid'), ('paid', 'Paid'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='testrequestdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('partly_billed', 'Partly Billed'), ('partly_paid', 'Partly Paid'), ('paid', 'Paid'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
