# Generated by Django 4.2.16 on 2026-05-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_testrequestdetail_mls_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
