# Generated by Django 5.2 on 2025-08-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_labresult_validated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
