# Generated by Django 4.2.16 on 2025-09-11 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_photo'),
        ('lab', '0004_subtest_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_requests', to='patients.patient'),
        ),
    ]
