# Generated by Django 4.2.16 on 2026-05-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_investigationrequest_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdetail',
            name='radiologist_comment',
            field=models.TextField(blank=True, help_text='Comments from radiologist/MLS about this investigation', null=True),
        ),
        migrations.AlterField(
            model_name='investigationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('partly_billed', 'Partly Billed'), ('partly_paid', 'Partly Paid'), ('paid', 'Paid'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('billed', 'Billed'), ('partly_billed', 'Partly Billed'), ('partly_paid', 'Partly Paid'), ('paid', 'Paid'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
