# Generated by Django 4.2.16 on 2026-05-03 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObstetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravida', models.PositiveIntegerField(help_text='Total number of pregnancies')),
                ('para', models.PositiveIntegerField(help_text='Number of births ≥ 24 weeks')),
                ('abortions', models.PositiveIntegerField(default=0)),
                ('living_children', models.PositiveIntegerField(default=0)),
                ('previous_c_section', models.BooleanField(default=False)),
                ('previous_stillbirth', models.BooleanField(default=False)),
                ('previous_neonatal_death', models.BooleanField(default=False)),
                ('pregnancy_complications', models.TextField(blank=True, null=True)),
                ('inter_pregnancy_interval', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstetric_history', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='UltrasoundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField()),
                ('gestational_age', models.PositiveIntegerField()),
                ('fetal_heartbeat', models.BooleanField(default=True)),
                ('number_of_fetuses', models.PositiveIntegerField(default=1)),
                ('placenta_position', models.CharField(blank=True, max_length=100, null=True)),
                ('amniotic_fluid', models.CharField(blank=True, max_length=100, null=True)),
                ('fetal_weight_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('scan_image', models.FileField(blank=True, null=True, upload_to='ultrasound_scans/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasounds', to='anc_specialty.obstetrichistory')),
            ],
        ),
        migrations.CreateModel(
            name='MenstrualGynecologicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_menstrual_period', models.DateField()),
                ('estimated_due_date', models.DateField()),
                ('cycle_regular', models.BooleanField(default=True)),
                ('cycle_length', models.PositiveIntegerField(blank=True, help_text='Cycle length in days', null=True)),
                ('contraceptive_history', models.TextField(blank=True, null=True)),
                ('gynecological_conditions', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menstrual_history', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalFamilyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypertension', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('asthma', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('family_genetic_disorders', models.TextField(blank=True, null=True)),
                ('other_medical_conditions', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('delivery_mode', models.CharField(choices=[('vaginal', 'Vaginal Delivery'), ('c_section', 'Caesarean Section'), ('assisted', 'Assisted Delivery')], max_length=50)),
                ('place_of_delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('complications', models.TextField(blank=True, null=True)),
                ('mother_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('baby_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('baby_sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('apgar_score_1min', models.PositiveIntegerField(blank=True, null=True)),
                ('apgar_score_5min', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='anc_specialty.obstetrichistory')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentPregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestational_age_weeks', models.PositiveIntegerField()),
                ('number_of_fetuses', models.PositiveIntegerField(default=1)),
                ('presenting_complaints', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('supplements', models.TextField(blank=True, null=True)),
                ('smoking', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_pregnancy', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='BabyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_number', models.PositiveIntegerField()),
                ('baby_sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('apgar_score_1min', models.PositiveIntegerField(blank=True, null=True)),
                ('apgar_score_5min', models.PositiveIntegerField(blank=True, null=True)),
                ('baby_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='anc_specialty.deliveryrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AntenatalVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=20)),
                ('pulse', models.PositiveIntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fundal_height', models.DecimalField(blank=True, decimal_places=2, help_text='in cm', max_digits=5, null=True)),
                ('fetal_heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('edema', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenatal_vitals', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ANCReVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('gestational_age', models.PositiveIntegerField(help_text='Gestational age in weeks')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('fetal_heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('fundal_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('complaints', models.TextField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anc_visits', to='anc_specialty.obstetrichistory')),
            ],
        ),
    ]
